import os
import uuid
import datetime
import pytz
from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from fastapi.responses import FileResponse

import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from database import engine, Base, get_db
import models
import schemas
import excel_manager

Base.metadata.create_all(bind=engine)

app = FastAPI(title="AttendX API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory session store for tokens generated by faculty.
# Format: { token_string: { "class_name": ..., "col_idx": ..., "expires_at": ... } }
active_sessions = {}
# Device tracking: { token_string: [device_id_1, device_id_2] }
scanned_devices = {}

def get_ist_time():
    ist = pytz.timezone('Asia/Kolkata')
    return datetime.datetime.now(ist)

@app.post("/api/student/signup")
def student_signup(student: schemas.StudentCreate, db: Session = Depends(get_db)):
    # Check if student exists in CMPN files before allowing signup?
    # For demo, allow registration if roll_number corresponds to one from text files.
    # Actually, we allow any valid roll number but we'll assign class dynamically or let them just sign up.
    # For simplicity, search roll number across text files to find their class.
    student_class = None
    for c in excel_manager.CLASSES:
        txt_path = os.path.join(excel_manager.BASE_DIR, f"{c}.txt")
        if os.path.exists(txt_path):
            with open(txt_path, "r", encoding="utf-8") as f:
                for line in f:
                    if line.startswith(student.roll_number):
                        student_class = c
                        break
        if student_class:
            break
            
    if not student_class:
        raise HTTPException(status_code=400, detail="Roll number not found in college database.")

    db_student = db.query(models.Student).filter(models.Student.roll_number == student.roll_number).first()
    if db_student:
        raise HTTPException(status_code=400, detail="Student already registered.")

    new_student = models.Student(
        roll_number=student.roll_number,
        password=student.password, # Plaintext for demo purposes
        student_class=student_class
    )
    db.add(new_student)
    db.commit()
    db.refresh(new_student)
    return {"message": "Signup successful", "student_class": student_class}

@app.post("/api/student/login")
def student_login(student: schemas.StudentCreate, db: Session = Depends(get_db)):
    db_student = db.query(models.Student).filter(
        models.Student.roll_number == student.roll_number,
        models.Student.password == student.password
    ).first()
    if not db_student:
        raise HTTPException(status_code=401, detail="Invalid credentials")
    return {"message": "Login successful", "roll_number": db_student.roll_number, "student_class": db_student.student_class}

@app.post("/api/faculty/signup")
def faculty_signup(faculty: schemas.TeacherCreate, db: Session = Depends(get_db)):
    db_faculty = db.query(models.Teacher).filter(models.Teacher.username == faculty.username).first()
    if db_faculty:
        raise HTTPException(status_code=400, detail="Username already taken.")

    new_faculty = models.Teacher(
        username=faculty.username,
        password=faculty.password
    )
    db.add(new_faculty)
    db.commit()
    return {"message": "Teacher signup successful"}

@app.post("/api/faculty/login")
def faculty_login(faculty: schemas.TeacherCreate, db: Session = Depends(get_db)):
    db_faculty = db.query(models.Teacher).filter(
        models.Teacher.username == faculty.username,
        models.Teacher.password == faculty.password
    ).first()
    if not db_faculty:
        raise HTTPException(status_code=401, detail="Invalid credentials")
    return {"message": "Login successful", "username": db_faculty.username}

@app.post("/api/faculty/generate_qr")
def generate_qr(req: schemas.GenerateSessionRequest):
    token = str(uuid.uuid4())
    ist_now = get_ist_time()
    expires_at = ist_now + datetime.timedelta(minutes=1) # Scanner limit to 1 minute
    
    session_info = f"{req.duration}HR {req.session_type}"
    col_idx = excel_manager.add_attendance_column(req.class_name, session_info)
    
    active_sessions[token] = {
        "class_name": req.class_name,
        "col_idx": col_idx,
        "expires_at": expires_at
    }
    scanned_devices[token] = []
    
    return {
        "token": token,
        "expires_at": expires_at.isoformat(),
        "class_name": req.class_name
    }

@app.post("/api/student/scan")
def scan_qr(req: schemas.ScanRequest, db: Session = Depends(get_db)):
    if req.session_token not in active_sessions:
        raise HTTPException(status_code=400, detail="Invalid or expired session.")
    
    session_data = active_sessions[req.session_token]
    
    # Check 1 minute expiry
    if get_ist_time() > session_data["expires_at"]:
        raise HTTPException(status_code=400, detail="QR code session has expired (1 minute limit).")
    
    # Check device ID
    if req.device_id in scanned_devices[req.session_token]:
        raise HTTPException(status_code=400, detail="This device has already marked attendance.")
        
    # Mark in Excel
    success = excel_manager.mark_attendance(session_data["class_name"], req.roll_number, session_data["col_idx"])
    
    if not success:
        raise HTTPException(status_code=400, detail="Roll number not found in this class.")
        
    scanned_devices[req.session_token].append(req.device_id)
    return {"message": "Attendance marked as present!"}

@app.get("/api/faculty/download/{class_name}")
def download_excel(class_name: str):
    file_path = os.path.join(excel_manager.BASE_DIR, f"{class_name}_Attendance.xlsx")
    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Excel file not found.")
    return FileResponse(path=file_path, filename=f"{class_name}_Attendance.xlsx", media_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')

from fastapi.staticfiles import StaticFiles

# Mount the static frontend files
frontend_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "frontend")
if os.path.exists(frontend_dir):
    app.mount("/", StaticFiles(directory=frontend_dir, html=True), name="frontend")
